name: Build Ruby SDK

on:
  pull_request:
    branches:
      - master

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  build_ruby:
    name: Build Ruby
    runs-on: ubuntu-22.04
    needs:
      - generate_schemas
      - build_rust

    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Download Ruby schemas artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: schemas.rb
          path: languages/ruby/schemas.rb

      #- name: Download x86_64-apple-darwin files
      #  uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      #  with:
      #    name: libbitwarden_c_files-x86_64-apple-darwin
      #    path: languages/ruby/macos-x64

      #- name: Download aarch64-apple-darwin files
      #  uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      #  with:
      #    name: libbitwarden_c_files-aarch64-apple-darwin
      #    path: languages/ruby/macos-arm64

      - name: Download x86_64-unknown-linux-gnu files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libbitwarden_c_files-x86_64-unknown-linux-gnu
          path: temp/ubuntu-x64

      - name: Copy Linux file
        run: |
          ls -lah
          pwd
          cd temp
          ls -lah
          cp temp/ubuntu-x64/libbitwarden.so languages/ruby/libbitwarden.so
        shell: bash

      - name: Clean up temporary files
        run: rm -rf temp/ubuntu-x64

      #- name: Download x86_64-pc-windows-msvc files
      #  uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      #  with:
      #    name: libbitwarden_c_files-x86_64-pc-windows-msvc
      #    path: languages/ruby/windows-x64

      - name: Set up Ruby
        uses: actions/checkout@v4
        with:
          ref: master
          path: languages/ruby

      - name: Install Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2'

      - name: Setup gem and release it
        run: |
          ls -la
          cd languages/ruby/languages/ruby
          ls -la
          gem install bundler
          gem build *.gemspec
          gem install *.gem
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}\n" > $HOME/.gem/credentials
          gem push *.gem

